# Generated by Django 2.2.12 on 2022-12-31 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deepdive', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='https://img.freepik.com/premium-vector/king-crown-esport-logo-design_177315-269.jpg', max_length=128),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('highlights', models.CharField(max_length=1024)),
                ('lowlights', models.CharField(max_length=1024)),
                ('emotions', models.CharField(max_length=1024)),
                ('knowledge', models.CharField(max_length=1024)),
                ('other', models.CharField(max_length=1024)),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
