# Generated by Django 2.2.12 on 2022-12-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepdive', '0003_auto_20221231_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
