# Generated by Django 2.2.12 on 2022-12-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepdive', '0004_auto_20221231_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='x', unique=True),
        ),
    ]
