# Generated by Django 2.2.12 on 2022-12-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepdive', '0006_auto_20221231_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzingpeople',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
